language: node_js
node_js:
  - 10
branches:
  only:
    # intended for /dev stage auto deployment
    - master
    # intended for /dev stage tag deployment
    - /^dev-.+$/
    # intended for /prod stage tag deployment
    - /^prod-.+$/
before_install:
  - npm install -g serverless
script:
  - npm run lint
  - ./scripts/deploy
env:
  global:
    - DEV_PGHOST: eq-dev-cluster.cluster-cx4wctygygyq.us-east-1.rds.amazonaws.com
    - DEV_PGDATABASE: EQAds
    - DEV_PGUSER: eqdev
    # DEV_PGPASSWORD - set in Travis UI
    - PROD_PGHOST: eq-db-prod.cluster-cx4wctygygyq.us-east-1.rds.amazonaws.com
    - PROD_PGDATABASE: EQAds
    - PROD_PGUSER: admin
    # PROD_PGPASSWORD - set in Travis UI
    # README_LOCUS_SECRET - set in Travis UI
    - OTP_TTL: 600000
    # DEV_JWT_SECRET - set in Travis UI
    # PROD_JWT_SECRET - set in Travis UI
    # SLACK_WEBHOOK for deployment status message
    - secure: "thHfHIpE4jRoeiD3rE7YOCbK4k+x7Lz56UaNFV7UPzplRdowbZSUnBbb28r9rAzOhwkF36/edMpvHVaZyTzug2ptyzgSj9gdZhnIH78MpeMxnBScfb3c1pBz8Xr68qBpmMfYPfv4kobggA+zC9lX92nalTk+RU5mYk9FXGZdsFsxNMCQhxltf5q2zerHIBVFjYFKotAIROl36AWJEdIMPPfRKKyD2UuQ3UIxDIjHEdSeFAzZ4GNz1Xmcxw2jegRX44ONptWQ7GHmxJ3HqfQU49q6PpozsD8/Txx/31seipujBc3bz+xE9ZSYpdzRSxOowN6tdpyPEHXmQUic4Xh3UPpqOkkp0MQ/7NbL31XrG2kEn51vM/5o+qdjsK4DrXlWHtEEJKLZ2AxBpcISNgZcLnp9uQXlNvfKSbRNy2VfvE+7xkG0bPLzhS7IlO0TLzVF1MmMNeDrjPLeoJsXaywObe/2UZlLbFcgXP7aGQa/Hdft6PQkgou1hZJr36MvWlc2WYx2ozJpXrN7PhLwA0BVi6d0DpTIZnoTpWR+PAlL9nYJmfdOZ2A/xp7yuheORTfItso20NULsPPWoTgHhcXHSFbjv55EJOhGitrs+KJxKwpzxFD3QBPD7UxRoqXH4/lGrj4A1DOlnxRWPigrXo0Vt0x4Cdg00A0vJFq51fcBlq0="
