service: keywarden

plugins:
  - serverless-domain-manager

custom:
  # CORS allowed headers
  allowedHeaders:
    - Content-Type
    - X-Amz-Date
    - Authorization
    - X-Api-Key
    - X-Amz-Security-Token
    - X-Amz-User-Agent
    - eq-api-user
    - eq-api-jwt
  customDomain:
    domainName: 'auth.eqworks.io'
    basePath: '${opt:stage, self:provider.stage}'
    stage: '${opt:stage, self:provider.stage}'
    certificateName: '*.eqworks.io'
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs8.10
  timeout: 30
  memorySize: 256
  environment:
    JWT_SECRET: ${env:JWT_SECRET}
    MONGO_URI: ${env:MONGO_URI}
    MONGO_USER_DB: ${env:MONGO_USER_DB}
    MONGO_USER_COLL: ${env:MONGO_USER_COLL}
    OTP_TTL: ${env:OTP_TTL}
    KEYWARDEN_VER: ${env:KEYWARDEN_VER}
    STAGE: ${opt:stage, self:provider.stage}
  vpc: # vpc-70658509 | EQ-DC-Tunnel
    securityGroupIds:
      - sg-081b437d # api-gateway-dc
    subnetIds:
      - subnet-b59ae9fe # EQ-DC-Lambda Public 1A
      - subnet-df12bb82 # EQ-DC-Lambda Public 1B
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: arn:aws:ses:us-east-1:175398475102:*

functions:
  index:
    handler: api.index
    events:
      - http:
          path: /
          cors: true
          method: get
  login:
    handler: api.login
    events:
      - http:
          path: login
          cors: true
          method: get
          request:
            parameters:
              querystrings:
                user: true
                redirect: false
  verify:
    handler: api.verify
    events:
      - http:
          path: verify
          cors: true
          method: get
          request:
            parameters:
              querystrings:
                user: true
                otp: true
  confirm:
    handler: api.confirm
    events:
      - http:
          path: confirm
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}
          method: get
          request:
            parameters:
              querystrings:
                light: false
              headers:
                eq-api-jwt: true
  refresh:
    handler: api.refresh
    events:
      - http:
          path: refresh
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}
          method: get
          request:
            parameters:
              headers:
                eq-api-jwt: true
