service: keywarden

custom:
  # this is [STAGE NAME]-env.yml, default to dev-env.yml
  envFile: ./${opt:stage, self:provider.stage}-env.yml

provider:
  name: aws
  runtime: nodejs6.10
  timeout: 30
  memorySize: 256
  environment: ${file(./${self:custom.envFile}):}
  vpc: # vpc-70658509 | EQ-DC-Tunnel
    securityGroupIds:
      - sg-081b437d # api-gateway-dc
    subnetIds:
      - subnet-b59ae9fe # EQ-DC-Lambda Public 1A
      - subnet-df12bb82 # EQ-DC-Lambda Public 1B
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: arn:aws:ses:us-east-1:175398475102:*

functions:
  login:
    handler: api.login
    events:
      - http:
          path: login
          cors: true
          method: get
          request:
            parameters:
              querystrings:
                user: true
                redirect: false
  verify:
    handler: api.verify
    events:
      - http:
          path: verify
          cors: true
          method: get
          request:
            parameters:
              querystrings:
                user: true
                otp: true
