#!/usr/bin/env bash

[ -z "$1" ] \
    && echo "No STAGE supplied" \
    && exit 1

[ $1 = "prod" ] || [ $1 = "dev" ] \
    && echo "Cannot deploy to prod or dev stages from local" \
    && exit 1

STAGE="$1"

# deploy script directory to anchor where to call deployment
DIR=$(dirname "${BASH_SOURCE[0]}")

cd "$DIR/.."

# retrieve information from local git
BRANCH=$(git rev-parse --abbrev-ref HEAD)
SERVICE_VER=$(git rev-parse --short HEAD)

echo -e "\n============= Deploying branch: ${BRANCH} (${SERVICE_VER}) to stage: ${STAGE}..."

# deploy with branch/stage specific env vars
DEPLOY_RES=$(bash -c "env $(print-env dev-env.yml) KEYWARDEN_VER=${SERVICE_VER} sls deploy --stage ${STAGE}")

echo "$DEPLOY_RES"
