name: Serverless deployment - dev stage

on:
  push:
    branches:
      - main
    tags:
      - 'dev-*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      STAGE: dev # also must have matching Portunus project/stage

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - run: python -m pip install print-env

      - name: Set Node.js version
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install serverless
        run: npm install -g serverless@3.39.0

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Deploy through serverless
        run: yarn deploy --stage ${STAGE}
        env:
          # aws creds for deployment
          AWS_ACCESS_KEY_ID: ${{ secrets.CD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CD_AWS_SECRET_ACCESS_KEY }}
          # keywarden API version, passthrough
          KEYWARDEN_VER: ${{ github.sha }}
          # for print-env
          PORTUNUS_TOKEN: ${{ secrets.CD_PORTUNUS_TOKEN_JWT }}/${{ github.event.repository.name }}/${{ env.STAGE }}

      - name: Notify on deployment status
        if: ${{ always() }}
        run: npx @eqworks/notify deployment ${GITHUB_REPOSITORY} --commit=${GITHUB_SHA} --stage=${STAGE} --status=${{ job.status }}
        env:
          SLACK_HOOK: ${{ secrets.CD_SLACK_HOOK }}
