name: Serverless deployment - prod stage

on:
  push:
    tags:
      - 'prod-*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      STAGE: prod # also must have matching Portunus project/stage

    steps:
      - uses: actions/checkout@v2

      - name: Set Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'

      - run: python -m pip install print-env

      - name: Set Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: npm install -g serverless
      - run: yarn install

      - name: Deploy through serverless
        run: yarn deploy --stage ${STAGE}
        env:
          # aws creds for deployment
          AWS_ACCESS_KEY_ID: ${{ secrets.CD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CD_AWS_SECRET_ACCESS_KEY }}
          # keywarden API version, passthrough
          KEYWARDEN_VER: ${{ github.sha }}
          # for print-env
          PORTUNUS_TOKEN: ${{ secrets.CD_PORTUNUS_TOKEN_JWT }}/${{ github.event.repository.name }}/${{ env.STAGE }}

      - name: Notify on deployment status
        if: ${{ always() }}
        run: npx @eqworks/notify deployment ${GITHUB_REPOSITORY} --commit=${GITHUB_SHA} --stage=${STAGE} --status=${{ job.status }}
        env:
          SLACK_HOOK: ${{ secrets.CD_SLACK_HOOK }}

      - name: Generate tag associated release notes
        run: npx @eqworks/release notes -v --pattern="prod-*" --head ${GITHUB_REF##*/} --github
        env:
          GITHUB_OWNER: EQWorks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify on release notes update
        if: ${{ success() }}
        run: npx @eqworks/notify send "Release notes updated for ${GITHUB_REPOSITORY} ${GITHUB_REF##*/}" --link "https://github.com/EQWorks/${GITHUB_REPOSITORY}/tag/${GITHUB_REF##*/}" --status ${{ job.status }}
        env:
          SLACK_HOOK: ${{ secrets.CD_SLACK_HOOK }}
